/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TG Game API
 * API for Telegram Game
 * OpenAPI spec version: 1.0
 */

export interface AttackDto {
  /** Attacker player id */
  attackerId: string;
  /** Defender player id */
  defenderId: string;
}
