/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TG Game API
 * API for Telegram Game
 * OpenAPI spec version: 1.0
 */

export type UpgradeStatsDtoStat = typeof UpgradeStatsDtoStat[keyof typeof UpgradeStatsDtoStat];


export const UpgradeStatsDtoStat = {
  strength: 'strength',
  defense: 'defense',
} as const;
