/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TG Game API
 * API for Telegram Game
 * OpenAPI spec version: 1.0
 */
import type { UpgradeStatsDtoStat } from './upgradeStatsDtoStat';

export interface UpgradeStatsDto {
  stat: UpgradeStatsDtoStat;
  /** Number of points to add */
  points: number;
}
