/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TG Game API
 * API for Telegram Game
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseDto,
  TelegramAuthDto,
  UserControllerGetUserParams
} from './model';

/**
 * @summary Get or create user by Telegram ID
 */
export type userControllerGetUserResponse200 = {
  data: ApiResponseDto
  status: 200
}

export type userControllerGetUserResponseSuccess = (userControllerGetUserResponse200) & {
  headers: Headers;
};
;

export type userControllerGetUserResponse = (userControllerGetUserResponseSuccess)

export const getUserControllerGetUserUrl = (params: UserControllerGetUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/user?${stringifiedParams}` : `/v1/user`
}

export const userControllerGetUser = async (params: UserControllerGetUserParams, options?: RequestInit): Promise<userControllerGetUserResponse> => {

  const res = await fetch(getUserControllerGetUserUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerGetUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as userControllerGetUserResponse
}





export const getUserControllerGetUserQueryKey = (params?: UserControllerGetUserParams,) => {
    return [
    `/v1/user`, ...(params ? [params] : [])
    ] as const;
    }


export const getUserControllerGetUserQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUser>>, TError = unknown>(params: UserControllerGetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUser>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUserQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUser>>> = ({ signal }) => userControllerGetUser(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetUserQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUser>>>
export type UserControllerGetUserQueryError = unknown


export function useUserControllerGetUser<TData = Awaited<ReturnType<typeof userControllerGetUser>>, TError = unknown>(
 params: UserControllerGetUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUser>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUser>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUser<TData = Awaited<ReturnType<typeof userControllerGetUser>>, TError = unknown>(
 params: UserControllerGetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUser>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUser>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUser<TData = Awaited<ReturnType<typeof userControllerGetUser>>, TError = unknown>(
 params: UserControllerGetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUser>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get or create user by Telegram ID
 */

export function useUserControllerGetUser<TData = Awaited<ReturnType<typeof userControllerGetUser>>, TError = unknown>(
 params: UserControllerGetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUser>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetUserQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get health status
 */
export type healthControllerGetHealthResponse200 = {
  data: ApiResponseDto
  status: 200
}

export type healthControllerGetHealthResponseSuccess = (healthControllerGetHealthResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetHealthResponse = (healthControllerGetHealthResponseSuccess)

export const getHealthControllerGetHealthUrl = () => {




  return `/v1/health`
}

export const healthControllerGetHealth = async ( options?: RequestInit): Promise<healthControllerGetHealthResponse> => {

  const res = await fetch(getHealthControllerGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerGetHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthControllerGetHealthResponse
}





export const getHealthControllerGetHealthQueryKey = () => {
    return [
    `/v1/health`
    ] as const;
    }


export const getHealthControllerGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerGetHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerGetHealth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerGetHealth>>> = ({ signal }) => healthControllerGetHealth({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerGetHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetHealth>>>
export type HealthControllerGetHealthQueryError = unknown


export function useHealthControllerGetHealth<TData = Awaited<ReturnType<typeof healthControllerGetHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerGetHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthControllerGetHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerGetHealth<TData = Awaited<ReturnType<typeof healthControllerGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerGetHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthControllerGetHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerGetHealth<TData = Awaited<ReturnType<typeof healthControllerGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerGetHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get health status
 */

export function useHealthControllerGetHealth<TData = Awaited<ReturnType<typeof healthControllerGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerGetHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Authenticate Telegram Web App initData
 */
export type authControllerAuthenticateResponse200 = {
  data: ApiResponseDto
  status: 200
}

export type authControllerAuthenticateResponseSuccess = (authControllerAuthenticateResponse200) & {
  headers: Headers;
};
;

export type authControllerAuthenticateResponse = (authControllerAuthenticateResponseSuccess)

export const getAuthControllerAuthenticateUrl = () => {




  return `/v1/auth/telegram`
}

export const authControllerAuthenticate = async (telegramAuthDto: TelegramAuthDto, options?: RequestInit): Promise<authControllerAuthenticateResponse> => {

  const res = await fetch(getAuthControllerAuthenticateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      telegramAuthDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerAuthenticateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerAuthenticateResponse
}




export const getAuthControllerAuthenticateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAuthenticate>>, TError,{data: TelegramAuthDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerAuthenticate>>, TError,{data: TelegramAuthDto}, TContext> => {

const mutationKey = ['authControllerAuthenticate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerAuthenticate>>, {data: TelegramAuthDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerAuthenticate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerAuthenticateMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerAuthenticate>>>
    export type AuthControllerAuthenticateMutationBody = TelegramAuthDto
    export type AuthControllerAuthenticateMutationError = unknown

    /**
 * @summary Authenticate Telegram Web App initData
 */
export const useAuthControllerAuthenticate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAuthenticate>>, TError,{data: TelegramAuthDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerAuthenticate>>,
        TError,
        {data: TelegramAuthDto},
        TContext
      > => {
      return useMutation(getAuthControllerAuthenticateMutationOptions(options), queryClient);
    }
