services:
  db:
    container_name : tg-game-back
    image : postgres:15.2
    restart : always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - tg-game-back-volume:/var/lib/postgresql/data
    networks:
      - tg-game-back-net

volumes:
  tg-game-back-volume:

networks:
  tg-game-back-net:
